databases:
- engine: PG
  name: shipping
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
name: shipping
region: fr
services:
- environment_slug: node-js
  envs:
  - key: APP_SECRET
    scope: RUN_TIME
    value: ${shipping.APP_SECRET}
  - key: ALGORITHM
    scope: RUN_AND_BUILD_TIME
    value: ${shipping.ALGORITHM}
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${shipping.DATABASE_URL}
  github:
    branch: master
    repo: biad-iritie/ShippingManageBack
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
  name: shipping-manage-back
  routes:
  - path: /api
  run_command: npm start
static_sites:
- build_command: npm run build
  environment_slug: node-js
  envs:
  - key: DATABASE_URL
    scope: BUILD_TIME
    value: ${shipping.DATABASE_URL}
  - key: API
    scope: BUILD_TIME
    value: ${shipping.API}
  github:
    branch: master
    repo: biad-iritie/ShippingManageFront
  name: mshipping
  routes:
  - path: /
  catchall_document: index.html